project: 
  type: website
  output-dir: docs

website:
  title: "Mary Palmer - Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://pal24032.github.io/mary-palmer-mp/
  repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Mary Palmer 2026©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/mary-palmer-mp/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleaning"
        file: cleaning.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Statistics"
        file: statistics.qmd
      - text: "Data Storytelling"
        file: storytelling.qmd
      - text: "Spreadsheet Analytics"
        file: spreadsheet.qmd
      - text: "Past Coursework"
        file: coursework.qmd


  sidebar: 
    - title: "Data Cleaning"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleaning"
          file: cleaning.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleaning_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleaning_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleaning_Projects/project3.qmd
        - text: "---"
    - title: "Past Coursework"
      style: "docked"
      background: light
      contents:
        - text: "Past Coursework"
          file: coursework.qmd
        - text: "---"
        - text: "Project 1"
          file: Coursework/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Coursework/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Coursework/project3.qmd
        - text: "---"
    - title: "Data Storytelling"
      style: "docked"
      background: light
      contents:
        - text: "Data Storytelling"
          file: storytelling.qmd
        - text: "---"
        - text: "Project 1"
          file: Storytelling/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Storytelling/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Storytelling/project3.qmd
        - text: "---"
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Machine Learning"
          file: ml.qmd
        - text: "---"
        - text: "Project 1"
          file: Machine_Learning/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Machine_Learning/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Machine_Learning/project3.qmd
        - text: "---"
    - title: "Statistics"
      style: "docked"
      background: light
      contents:
        - text: "Full Stack"
          file: statistics.qmd
        - text: "---"
        - text: "Project 1"
          file: Statistics/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Statistics/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Statistics/project3.qmd
        - text: "---"
    - title: "Spreadsheet Analytics"
      style: "docked"
      background: light
      contents:
        - text: "Spreadsheet Analytics"
          file: spreadsheet.qmd
        - text: "---"
        - text: "Project 1"
          file: Spreadsheet/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Spreadsheet/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Spreadsheet/project3.qmd
        - text: "---"

  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



